apiVersion: v1
kind: Secret
metadata:
  name: kafka-ops-secrets
  namespace: kafka-ops
  labels:
    app.kubernetes.io/name: kafka-ops-agent
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-password: a2Fma2Ffb3BzX3Bhc3N3b3Jk  # kafka_ops_password
  api-key: YWRtaW4tc2VjcmV0LWtleQ==  # admin-secret-key
  jwt-secret: and0LXNlY3JldC1rZXktZm9yLWp3dA==  # jwt-secret-key-for-jwt
  
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-ops-tls
  namespace: kafka-ops
  labels:
    app.kubernetes.io/name: kafka-ops-agent
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key - replace with actual values
  tls.crt: LS0tLS1CRUdJTi...  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi...  # Base64 encoded private key